services:
  mailserver:
    build:
      context: ./mail-server
    container_name: mail-server
    hostname: mail.local
    domainname: mail.local
    volumes:
      - ./mail-server/home:/home
      - logs:/app/logs
    ports:
      - "3005:3005"
      - "143:143"
      - "587:587"
      - "993:993"
    restart: always
    networks:
      - dmail-net

  server:
    build: ./server
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    depends_on:
      - mailserver
    volumes:
      - ./uploads:/app/uploads
      - logs:/app/logs
    networks:
      - dmail-net

  client:
    build: ./client
    ports:
      - "80:80"
    env_file:
      - ./client/.env
    depends_on:
      - server
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
    - dmail-net

volumes:
  logs:

networks:
  dmail-net:
    driver: bridge