services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server/uploads:/app/uploads
    env_file:
      - ./server/.env

  client:
    build: ./client
    ports:
      - "3000:80"
    env_file:
      - ./client/.env
    depends_on:
      - server
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf